### ISSUE TITLE
undefined method 'salt_install_type=' for #<VagrantPlugins::Salt::Config:0x000001008cc138> (NoMethodError)

### ISSUE THREAD

**Issue by raddevon** [notanumber/django-vagrant#1]
I get this error when I try to bring up the Vagrant VM:

```
Vagrantfile:15:in `block (2 levels) in <top (required)>': undefined method `salt_install_type=' for #<VagrantPlugins::Salt::Config:0x000001008cc138> (NoMethodError)
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v2/config/vm_provisioner.rb:42:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v2/config/vm_provisioner.rb:42:in `initialize'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v2/config/vm.rb:154:in `new'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v2/config/vm.rb:154:in `provision'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v1/config/vm.rb:146:in `block in upgrade'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v1/config/vm.rb:145:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/kernel_v1/config/vm.rb:145:in `upgrade'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/v2/loader.rb:112:in `block in upgrade'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/v2/loader.rb:110:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/v2/loader.rb:110:in `upgrade'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/loader.rb:124:in `block (3 levels) in load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/loader.rb:118:in `upto'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/loader.rb:118:in `block (2 levels) in load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/loader.rb:98:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/loader.rb:98:in `block in load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/loader.rb:95:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/config/loader.rb:95:in `load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:238:in `config_global'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:443:in `block in action_runner'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:28:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:28:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:251:in `hook'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:131:in `initialize'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/bin/vagrant:53:in `new'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/bin/vagrant:53:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

Any idea how I might get around this?

**Comment by notanumber** [comment]
Hmm.  Thinking there must be some incompatibilities between the newer Vagrant and the Salt plugin.

I'm seeing something similar after upgrading to Vagrant 1.2.0 and vagrant-salt 0.4.0

Vagrantfile:8:in `block in <top (required)>': undefined method`synced_folder' for #VagrantPlugins::Kernel_V1::VMConfig:0x00000101330a98 (NoMethodError)
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/config/v1/loader.rb:37:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/config/v1/loader.rb:37:in`load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/config/loader.rb:104:in `block (2 levels) in load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/config/loader.rb:98:in`each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/config/loader.rb:98:in `block in load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/config/loader.rb:95:in`each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/config/loader.rb:95:in `load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/environment.rb:259:in`config_global'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/environment.rb:493:in `block in action_runner'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/action/runner.rb:28:in`call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/action/runner.rb:28:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/environment.rb:272:in`hook'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/lib/vagrant/environment.rb:135:in `initialize'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/bin/vagrant:62:in`new'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.2.0/bin/vagrant:62:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in`load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'

**Comment by notanumber** [comment]
Right, so removing all traces of Vagrant from my system and re-installing from the packages seems to have corrected the first issue.  Now, running in to an issue where state.highstate appears to hang.  Will need to debug further.

**Comment by notanumber** [comment]
Ok.  All issues arising from new versions should be corrected.  everythin has been tested and confirmed to work with Vagrant 1.2.0, Vagrant-Salt 0.4.0, Virtualbox 4.2.12.

Let me know if there's still a problem at your end.
