### ISSUE TITLE
Permissions Issues (Errno 13)

### ISSUE THREAD

**Issue by cdownard** [notanumber/django-vagrant#2]
I setup a vagrant using your commands listed and then used vagrant ssh to get in and workon <project_name>. After that I had to sudo django-admin.py startapp testapp to get startapp to work.

When using stuff like south, django-admin.py schemamigration appname errors out due to permissions. sudo django-admin.py schemamigration appname returns schemamigration command not found.

Just curious how to get around this or how you work with it?

**Comment by notanumber** [comment]
Hi Christopher,

Thanks for the heads up on this.  I've updated the folder permissions in
the Vagrantfile so they should be properly applied now.

David

**Comment by notanumber** [comment]
Fixed in 516b3037fa7c1e890a40a635593ade90d4976b65
