### ISSUE TITLE
No manage.py and out of date requirements

### ISSUE THREAD

**Issue by wldcordeiro** [notanumber/django-vagrant#4]
I found your django-vagrant template and noticed that the requirements are all several versions behind, as well as a lack of a manage.py file and improperly configured database settings (couldn't the local settings be filled out automatically since we define those in the salt files?) I'm working on an update to send as a pull request but I want to get your ideas.

**Comment by notanumber** [comment]
Personally, I don't use `manage.py` as I've had issues getting to work properly with environment variables.  I'm not adverse to including it if it works though.

I'm not sure I understand what you mean by improperly configured database settings.  I've been using this setup on several projects and never run into an issue here.  Could you elaborate?  The `settings.foo.py` settings don't specify a database as there's no need. By default, the Postgresql connection will be a Unix domain socket.  Django will use `project_name` for the `USER` and `NAME` values in `DATABASE`, so it's one less thing to configure.  There's also no need for a `PASSWORD` value if we're using a socket, and therefore now no need to worry about accidentally checking in your password credentials when using source control.

I'd love to see improvements to the setup, so feel free to send pull requests!

**Comment by wldcordeiro** [comment]
I'm still working on testing my setup but so far I've had issues when I connect to the vagrant vm. It immediately spits this out, I'm not sure if you've seen this. 
https://gist.github.com/wldcordeiro/10080646

As far as the settings, I'm not sure I understand how you have them setup, wouldn't the vagrant.py settings file and local.py settings files be for the same use case?

**Comment by notanumber** [comment]
Hmm, that error looks familiar to one I've seen before.  Are you using the
latest code?  I could have sworn I corrected a permission based issue a
little while back.

The local.py you see in the settings folder is meant to be used by folks
that didn't want to use the Vagrant setup.  Sometimes I need to share
projects with people that don't want or can't install Vagrant for various
reason. In that case, I just have them use the point their setup to
settings.local when they're running the test server, eg. `django-admin.py
runserver --settings=foo.settings.local`

The VMs pre-configured to to use settings.vagrant through the use of an
environment variable in `.bashrc`

I should also note that I haven't yet had time to test any of this using
the latest Vagrant setup.  I believe the latest is 1.3?  I'm still on 1.2.

David

**Comment by wldcordeiro** [comment]
I'm not having luck getting rid of that error, but thanks for clarifying what the different settings files are for. Personally I've used the pattern where you use a try/except block inside the **init**.py file of your settings folder. Something like this. https://gist.github.com/wldcordeiro/10439870 

Looking into Vagrant though it looks like the newest version is 1.5.2. I was using 1.4.3 and have upgraded now I'm trying to get the setup to work with the latest release. Do you have any suggestions as to what to do to fix the permissions issue?
